services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_bad_design_lab
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=VeryStrongPassword123!
      - MSSQL_PID=Developer
    ports:
      - "1436:1433"
    volumes:
      - mssql_bad_design_data:/var/opt/mssql
    restart: unless-stopped

  sql-runner:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - mssql

volumes:
  mssql_bad_design_data:
