services:
  thread-types-api:
    build:
      context: ./ThreadTypesApi
    container_name: thread-types-api
    environment:
      APP_URL: http://0.0.0.0:8091
    ports:
      - "8091:8091"
    deploy:
      resources:
        limits:
          cpus: '1.0'

  k6:
    image: grafana/k6:0.49.0
    container_name: thread-types-k6
    volumes:
      - ./k6:/scripts
      - ./results:/results
    profiles:
      - tools
